plugins:
  - jemoji

theme: jekyll-theme-cayman

theme_color: "#7367ef"

format: web

favicon: favicon.ico

toc:
  - title: Group 1
    subfolderitems:
      - page: Thing 1
        url: /thing1.html
      - page: Thing 2
        url: /thing2.html
      - page: Thing 3
        url: /thing3.html
  - title: Group 2
    subfolderitems:
      - page: Piece 1
        url: /piece1.html
      - page: Piece 2
        url: /piece2.html
      - page: Piece 3
        url: /piece3.html
  - title: Group 3
    subfolderitems:
      - page: Widget 1
        url: /widget1.html
      - page: Widget 2
        url: /widget2.html
      - page: Widget 3
        url: /widget3.html

use_logo: true

github:
  is_project_page: true

logo: assets/logo512.png

use_text_title: false

search_in_topnav: true

show_feedback: true

feedback_email: rodolphe.a@gmail.com

title: My Meditation Time # title to appear in nav bar and page meta

description: Application simple et intuitive d’initiation et de pratique à la méditation! # Displays as site description meta tag for site

copyright: 2021 rodolphe Augusto, Inc. # appears in footer
