plugins:
  - jemoji

theme: jekyll-theme-cayman

theme_color: "#7367ef"

format: web

favicon: favicon.ico

use_logo: true

github:
  is_project_page: true

logo: assets/logo512.png

use_text_title: false

search_in_topnav: true

show_feedback: true

feedback_email: rodolphe.a@gmail.com

title: My Meditation Time # title to appear in nav bar and page meta

description: Application simple et intuitive d’initiation et de pratique à la méditation! # Displays as site description meta tag for site

copyright: 2021 rodolphe Augusto, Inc. # appears in footer
