plugins:
  - jemoji

theme: jekyll-theme-cayman

format: web

favicon: favicon.ico

use_logo: true

logo: demo/logo.png

use_text_title: false

search_in_topnav: true

show_feedback: true

feedback_email: rodolphe.a@gmail.com

title: My Mediation Time # title to appear in nav bar and page meta

description: Application d’initiation et de pratique à la méditation simple et intuitive # Displays as site description meta tag for site

copyright: 2021 rodolphe Augusto, Inc. # appears in footer
